### ISSUE TITLE
Research PHP Login Systems

### ISSUE THREAD

**Issue by tmoon8730** [EuterpeSolutions/Faithful-Scholars#25]
Figure out what the best way to do a PHP login system is

- [ ] Add sign up form

- [ ] Generate salt from sign up data

- [x] Security Questions

- [x] Recover Password

**Comment by tmoon8730** [comment]
http://www.johnmorrisonline.com/build-php-login-form-using-sessions/

**Comment by tmoon8730** [comment]
Research for implementing #10

**Comment by EmperorMoose** [comment]
http://codingcyber.org/simple-login-script-php-and-mysql-64/

**Comment by EmperorMoose** [comment]
https://github.com/therecluse26/PHP-Login

Open source php login

**Comment by EmperorMoose** [comment]
http://phpeasystep.com/phptu/6.html

Implemented this tutorial in login_research, but altered for php 7. This is not a secure example, but it works.

**Comment by EmperorMoose** [comment]
Security Needed

- SQL Injection: Strip slashes and use prepared statements
- Pass Protecton: Generate each user a p_salt based upon their inputting information. Salt_Salt will be a permutation of the name of the site. It is static. Pass stored in db will be hash of pass+site_salt+p_salt. When user logs, retreive p_salt from db, check pass from db against hash of inputted pass+site_salt+p_salt
-Session Hijacking: https://stackoverflow.com/questions/12233406/preventing-session-hijacking

**Comment by EmperorMoose** [comment]
Can log in. Uses salted hashes and sql injections protection. Half of reset password ability is there

**Comment by EmperorMoose** [comment]
Second half of reset forms created. Needs STMP configuration
