### ISSUE TITLE
Research PDF Generation

### ISSUE THREAD

**Issue by tmoon8730** [EuterpeSolutions/Faithful-Scholars#26]
Research how to generate a PDF with information filled in from a DB

- [x] Generate a PDF
- [x] Display it to the user so they can either download it or print it
- [x] Insert info onto PDF from a MySQL DB
- [ ] implement PDF gen on letters

This can be just a simple PHP file with dummy data in it for now

**Comment by EmperorMoose** [comment]
http://www.fpdf.org/

Popular library for doing this

**Comment by EmperorMoose** [comment]
https://www.web-development-blog.com/archives/create-pdf-files-with-php/

List of libraries which do this

**Comment by Alcamech** [comment]
@EmperorMoose Thanks, I've been looking into both of those.

**Comment by Alcamech** [comment]
Update: on my localhost, I was able to get a LAMP stack going and using FPDF I can generate a pdf and have it available for download. I will look into getting info from a db onto the generated pdf.
