### ISSUE TITLE
PDF Membership Card

### ISSUE THREAD

**Issue by tmoon8730** [EuterpeSolutions/Faithful-Scholars#51]
New feature requested by the client to add another PDF for the membership card. This could be shown off the Membership Letter page. 

- [x] Generate new Membership Card
- [x] Kates number, Faithful Scholars url
- [x] Generate text, family name and address
- [x] Instructions for basic laminating?

**Comment by Alcamech** [comment]
@tmoon8730 how should this membership card look ?

**Comment by Alcamech** [comment]
Need to complete the info generated from the db and add instructions for the membership card.
